spring:
  application:
    name: bumaview8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${JWT_SECRET_KEY}

server:
  port: 8080

front:
  base-url: ${FRONT_BASE_URL}